def on_forever():
    Tinybit.car_ctrl(Tinybit.CarState.CAR_RUN)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_BACK)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_LEFT)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_RIGHT)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_SPINLEFT)
    basic.pause(1000)
    Tinybit.car_ctrl(Tinybit.CarState.CAR_SPINRIGHT)
    basic.pause(1000)
basic.forever(on_forever)
